name: demo3
on: [workflow_dispatch, push]

jobs:
    check-self-hosted:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
            - run: ls -lart
            - run: pwd && la -la
